export const analyses = [
  {
    slug: 'galatasaray-433-pressing-analizi',
    title: 'Galatasaray\'ın 4-3-3 Yüksek Pressing Sistemi',
    subtitle: 'Okan Buruk döneminde yapısal dönüşüm ve pressing tetikleyicileri',
    category: 'Takım Analizi',
    formation: '4-3-3',
    team: 'Galatasaray',
    opponent: 'Fenerbahçe',
    result: '2-1',
    competition: 'Süper Lig',
    date: '2024-02-04',
    readTime: 12,
    tags: ['pressing', 'yüksek hat', 'geçiş oyunu'],
    coverColor: '#E8173A',
    featured: true,
    excerpt: 'Okan Buruk\'un 4-3-3 sisteminde ön press yapısı, pressing tetikleyicileri ve rakip top alışında geçiş hızı inceleniyor.',
  },
  {
    slug: 'fenerbahce-pozisyonel-oyun',
    title: 'Fenerbahçe\'nin Pozisyonel Yapılanması',
    subtitle: 'İsmail Kartal\'ın 4-2-3-1 sistemi: kanat kullanımı ve merkez yoğunluğu',
    category: 'Takım Analizi',
    formation: '4-2-3-1',
    team: 'Fenerbahçe',
    opponent: 'Trabzonspor',
    result: '3-0',
    competition: 'Süper Lig',
    date: '2024-01-28',
    readTime: 9,
    tags: ['pozisyonel oyun', 'kanat', 'çift pivot'],
    coverColor: '#003F8C',
    featured: true,
    excerpt: 'Fenerbahçe\'nin pozisyonel üstünlük kurma prensipleri, kanat yoğunluğu ve çift pivot kullanımı üzerine derinlemesine inceleme.',
  },
  {
    slug: 'real-madrid-gecis-hizi',
    title: 'Real Madrid\'in Geçiş Hızı Anatomisi',
    subtitle: 'Ancelotti\'nin 4-4-2 savunmasından 4-3-3 hücumuna anlık geçiş yapısı',
    category: 'Taktik Konsept',
    formation: '4-3-3',
    team: 'Real Madrid',
    opponent: 'Manchester City',
    result: '3-3',
    competition: 'UEFA Şampiyonlar Ligi',
    date: '2024-02-21',
    readTime: 15,
    tags: ['geçiş', 'counter-press', 'Vinicius'],
    coverColor: '#7C5CBF',
    featured: false,
    excerpt: 'Ancelotti döneminin geçiş oyunu anatomisi: top kaybında anlık baskı, kanat geçişleri ve Bellingham\'ın merkezi rolü.',
  },
  {
    slug: 'trabzonspor-311-savunma',
    title: 'Trabzonspor\'un 3-1-1 Alçak Savunma Bloğu',
    subtitle: 'Kompakt blok organizasyonu ve kanat kapama mekanizmaları',
    category: 'Savunma Analizi',
    formation: '3-5-2',
    team: 'Trabzonspor',
    opponent: 'Beşiktaş',
    result: '1-0',
    competition: 'Süper Lig',
    date: '2024-01-14',
    readTime: 7,
    tags: ['alçak blok', 'kompakt', 'counter'],
    coverColor: '#8B1A1A',
    featured: false,
    excerpt: 'Trabzonspor\'un alçak savunma organizasyonu, 5-4-1 şeklinde şekillenen blok ve ani geçiş anlarında kanat hızı analizi.',
  },
  {
    slug: 'besiktas-ikileme-stratejileri',
    title: 'Beşiktaş\'ın Çiftleme ve İkileme Stratejileri',
    subtitle: 'Orta saha çiftlemesi, kanat sıkıştırma ve press çıkış yolları',
    category: 'Orta Saha Analizi',
    formation: '4-3-3',
    team: 'Beşiktaş',
    opponent: 'Sivasspor',
    result: '2-2',
    competition: 'Süper Lig',
    date: '2024-01-07',
    readTime: 10,
    tags: ['ikilem', 'orta saha', 'press çıkışı'],
    coverColor: '#1A1A2E',
    featured: false,
    excerpt: 'Beşiktaş\'ın orta saha ikilemeleri, rakip yapı bozmaya yönelik çiftleme stratejileri ve baskı altında top çıkarma prensipleri.',
  },
  {
    slug: 'arsenal-yuksek-hat-savunma',
    title: 'Arsenal\'in Yüksek Hat Savunması: Risk ve Kazanım',
    subtitle: 'Arteta\'nın savunma hattı konumlanması ve offside tuzağı kullanımı',
    category: 'Savunma Analizi',
    formation: '4-3-3',
    team: 'Arsenal',
    opponent: 'Liverpool',
    result: '1-2',
    competition: 'Premier Lig',
    date: '2024-02-10',
    readTime: 11,
    tags: ['yüksek hat', 'offside tuzağı', 'Arteta'],
    coverColor: '#EF0107',
    featured: false,
    excerpt: 'Arteta\'nın yüksek savunma hattı konsepti, offside tuzağının kurulması ve bu sistemin karşılaştığı riskler üzerine kapsamlı analiz.',
  },
]

export const formations = [
  {
    id: '4-3-3',
    name: '4-3-3',
    category: 'Hücum Ağırlıklı',
    description: 'Geniş kanat kullanımı ve üçlü orta saha kontrolüyle dengeli bir sistem.',
    strengths: ['Kanat genişliği', 'Orta saha baskısı', 'Esnek geçiş'],
    weaknesses: ['Kanat arkası açık', 'Tek DM yüksek yük', 'İkilemeye açık'],
    famousTeams: ['Barcelona (Guardiola)', 'Liverpool (Klopp)', 'Galatasaray'],
    positions: [
      { id: 'gk', label: 'KK', x: 50, y: 88 },
      { id: 'rb', label: 'SB', x: 82, y: 70 },
      { id: 'rcb', label: 'ST', x: 63, y: 73 },
      { id: 'lcb', label: 'ST', x: 37, y: 73 },
      { id: 'lb', label: 'SB', x: 18, y: 70 },
      { id: 'rcm', label: 'OS', x: 70, y: 52 },
      { id: 'cm', label: 'OS', x: 50, y: 48 },
      { id: 'lcm', label: 'OS', x: 30, y: 52 },
      { id: 'rw', label: 'SK', x: 80, y: 28 },
      { id: 'st', label: 'FW', x: 50, y: 20 },
      { id: 'lw', label: 'SK', x: 20, y: 28 },
    ],
  },
  {
    id: '4-2-3-1',
    name: '4-2-3-1',
    category: 'Dengeli',
    description: 'Çift pivot güvencesiyle ofansif orta saha yaratıcılığını birleştiren sistem.',
    strengths: ['Merkez güvenliği', 'On numara yaratıcılığı', 'Çift pivot koruması'],
    weaknesses: ['Kanat izolasyonu', 'Top kayıplarında 2v2 riski', 'Kanat geçişine bağımlı'],
    famousTeams: ['Fenerbahçe', 'Almanya (2010)', 'Chelsea (Mourinho)'],
    positions: [
      { id: 'gk', label: 'KK', x: 50, y: 88 },
      { id: 'rb', label: 'SB', x: 82, y: 70 },
      { id: 'rcb', label: 'ST', x: 63, y: 73 },
      { id: 'lcb', label: 'ST', x: 37, y: 73 },
      { id: 'lb', label: 'SB', x: 18, y: 70 },
      { id: 'rdm', label: 'DM', x: 63, y: 57 },
      { id: 'ldm', label: 'DM', x: 37, y: 57 },
      { id: 'rw', label: 'SK', x: 75, y: 38 },
      { id: 'cam', label: '10', x: 50, y: 36 },
      { id: 'lw', label: 'SK', x: 25, y: 38 },
      { id: 'st', label: 'FW', x: 50, y: 20 },
    ],
  },
  {
    id: '3-5-2',
    name: '3-5-2',
    category: 'Kanat Bağımlı',
    description: 'Üçlü savunma ve kanat hücum oyuncularıyla geniş alan kontrolü.',
    strengths: ['Geniş alan kontrolü', 'Sayısal üstünlük', 'Savunma sağlamlığı'],
    weaknesses: ['Kanat arkası açık', 'Kanat yorgunluğu', 'Hızlı geçişlere açık'],
    famousTeams: ['Trabzonspor', 'Inter (Conte)', 'Juventus (Allegri)'],
    positions: [
      { id: 'gk', label: 'KK', x: 50, y: 88 },
      { id: 'rcb', label: 'ST', x: 72, y: 73 },
      { id: 'cb', label: 'ST', x: 50, y: 76 },
      { id: 'lcb', label: 'ST', x: 28, y: 73 },
      { id: 'rwb', label: 'KH', x: 88, y: 52 },
      { id: 'rcm', label: 'OS', x: 68, y: 50 },
      { id: 'cm', label: 'OS', x: 50, y: 46 },
      { id: 'lcm', label: 'OS', x: 32, y: 50 },
      { id: 'lwb', label: 'KH', x: 12, y: 52 },
      { id: 'rst', label: 'FW', x: 65, y: 22 },
      { id: 'lst', label: 'FW', x: 35, y: 22 },
    ],
  },
]

export const videos = [
  {
    id: 1,
    title: 'Gegenpressing Nedir? Klopp\'un Sistemi',
    subtitle: 'Top kaybı sonrası 6 saniye baskı prensibi ve organizasyonu',
    category: 'Taktik Konsept',
    duration: '18:42',
    views: '24.3K',
    date: '2024-02-15',
    tags: ['gegenpressing', 'Klopp', 'Liverpool'],
    thumbnailColor: '#C8102E',
    youtubeId: null,
  },
  {
    id: 2,
    title: 'False 9 Pozisyonunun Anatomisi',
    subtitle: 'Messi\'nin dönem tanımlayan rolünü taktik perspektifle anlıyoruz',
    category: 'Pozisyon Analizi',
    duration: '22:15',
    views: '31.8K',
    date: '2024-02-08',
    tags: ['false 9', 'Messi', 'Barcelona'],
    thumbnailColor: '#004D98',
    youtubeId: null,
  },
  {
    id: 3,
    title: 'Terzismo: 3 Savunucu Sistemin Evrimi',
    subtitle: 'Sacchi\'den Conte\'ye üçlü savunma bloğunun 30 yıllık yolculuğu',
    category: 'Sistem Analizi',
    duration: '31:07',
    views: '18.6K',
    date: '2024-01-30',
    tags: ['3-5-2', 'İtalya okulu', 'Conte'],
    thumbnailColor: '#003087',
    youtubeId: null,
  },
  {
    id: 4,
    title: 'Süper Lig\'de Pressing Kültürü',
    subtitle: 'Türk futbolunda yüksek pressing anlayışının gelişimi ve örnekleri',
    category: 'Süper Lig',
    duration: '14:55',
    views: '42.1K',
    date: '2024-01-22',
    tags: ['Süper Lig', 'pressing', 'Türkiye'],
    thumbnailColor: '#E30A17',
    youtubeId: null,
  },
]

export const scoutReports = [
  {
    id: 1,
    playerName: 'Arda Güler',
    age: 19,
    nationality: 'Türkiye',
    position: 'Sağ Kanat / On Numara',
    team: 'Real Madrid',
    league: 'La Liga',
    season: '2023-24',
    overallRating: 84,
    potential: 92,
    reportDate: '2024-02-20',
    analyst: 'TL Scouting',
    summary: 'Son derece yetenekli bir teknik oyuncu. Dar alanlarda top kontrolü, çevikliği ve yaratıcı pas atma becerisi üst düzey. Büyük kulübe uyum süreci beklenenin üstünde seyretmekte.',
    attributes: {
      teknik: 88, vizyon: 85, hız: 76, fizik: 68, savunma: 52, mentaliite: 80,
    },
    strengths: ['Dar alan driblingi', 'Uzak mesafe şutu', 'Pas kalitesi', 'Oyun zekası'],
    weaknesses: ['Fiziksel güç', 'Hava topu', 'Savunmaya katkı'],
    verdict: 'Takip Et',
  },
  {
    id: 2,
    playerName: 'Orkun Kökçü',
    age: 23,
    nationality: 'Hollanda / Türkiye',
    position: 'Merkez / On Numara',
    team: 'Benfica',
    league: 'Primeira Liga',
    season: '2023-24',
    overallRating: 80,
    potential: 86,
    reportDate: '2024-02-14',
    analyst: 'TL Scouting',
    summary: 'Taşıyıcı karakterde bir merkez oyuncusu. Press altında top koruma, üçüncü alan organizasyonu ve uzaktan şut kapasitesi öne çıkan özellikleri. Liderlik kabiliyeti gelişiyor.',
    attributes: {
      teknik: 82, vizyon: 84, hız: 73, fizik: 74, savunma: 66, mentaliite: 78,
    },
    strengths: ['Top taşıma', 'Vizyon & pas', 'Uzak şut', 'Liderlik'],
    weaknesses: ['Hız üstünlüğü yok', 'Maç sonunda düşüş', 'Hava topu'],
    verdict: 'İzlemeye Devam',
  },
  {
    id: 3,
    playerName: 'Baris Alper Yılmaz',
    age: 24,
    nationality: 'Türkiye',
    position: 'Sol Kanat',
    team: 'Galatasaray',
    league: 'Süper Lig',
    season: '2023-24',
    overallRating: 78,
    potential: 83,
    reportDate: '2024-02-05',
    analyst: 'TL Scouting',
    summary: 'Patlayıcı hız ve kanat geçişiyle dikkat çeken bir oyuncu. Birebir durumlar ve top sürerken alınan pozisyonlar başarılı. Son pas ve şut isabetinde tutarsızlık var.',
    attributes: {
      teknik: 79, vizyon: 72, hız: 90, fizik: 76, savunma: 61, mentaliite: 74,
    },
    strengths: ['Hız & ivme', 'Kanat geçişi', 'Birebir', 'Enerji'],
    weaknesses: ['Son pas tutarsız', 'Şut tercihleri', 'Press altında kayıp'],
    verdict: 'Potansiyel Var',
  },
]

export const getAnalysisBySlug = (slug) => analyses.find(a => a.slug === slug)
